# Generated by Django 6.0.3 on 2026-05-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
