# Generated by Django 6.0.3 on 2026-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="accounts.profile"
            ),
        ),
    ]
