# Generated by Django 6.0.3 on 2026-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="life", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="post_image"
            ),
        ),
    ]
