# Generated by Django 6.0.3 on 2026-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
