# Generated by Django 6.0.3 on 2026-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_comment_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
